apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
 name:  trustee-operator-catalog
 namespace: olm
spec:
 displayName: Trustee Operator Catalog
 sourceType: grpc
 image:  quay.io/rh_ee_lmilleri/trustee-operator-catalog:v0.1.0
 updateStrategy:
   registryPoll:
      interval: 5m
