apiVersion: v1
kind: Pod
metadata:
  name: kbs-client-2
spec:
  # runtimeClassName: kata-cc-sim
  containers:
  - name: kbs-client
    image: quay.io/confidential-containers/kbs-client:latest
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "360000"
    env:
      - name: RUST_LOG
        value:  none
