apiVersion: confidentialcontainers.org/v1alpha1
kind: KbsConfig
metadata:
  labels:
    app.kubernetes.io/name: kbsconfig
    app.kubernetes.io/instance: kbsconfig-sample
    app.kubernetes.io/part-of: kbs-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kbs-operator
  name: kbsconfig-sample
  namespace: kbs-operator-system
spec:
  kbsConfigMapName: kbs-config-grpc
  kbsAsConfigMapName: as-config-grpc
  kbsRvpsConfigMapName: rvps-config-grpc
  kbsAuthSecretName: kbs-auth-public-key
  kbsServiceType: ClusterIP
  kbsDeploymentType: MicroservicesDeployment
  kbsRvpsRefValuesConfigMapName: rvps-reference-values-sample
  kbsSecretResources: ["kbsres1"]
  # HTTPS support
  kbsHttpsKeySecretName: kbs-https-key
  kbsHttpsCertSecretName: kbs-https-certificate
  kbsResourcePolicyConfigMapName: resource-policy-sample
  tdxConfigSpec:
    kbsTdxConfigMapName: tdx-config-sample
